// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArofxRV-l8JJMdXPK4CrqrzGH55dR1XPk',
    appId: '1:458041467333:web:bbc94b740592d7f73c6bac',
    messagingSenderId: '458041467333',
    projectId: 'roomrent-72633',
    authDomain: 'roomrent-72633.firebaseapp.com',
    storageBucket: 'roomrent-72633.firebasestorage.app',
    measurementId: 'G-M2TTHM0B8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwS5xDHY--p0aSjGFImnLP0TqtuRUHQ-s',
    appId: '1:458041467333:android:2ccdd39f843b99453c6bac',
    messagingSenderId: '458041467333',
    projectId: 'roomrent-72633',
    storageBucket: 'roomrent-72633.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZM4-Vu9n4ITa6OSQgVs8AdqbziYlITs',
    appId: '1:458041467333:ios:dc521ad26943dcad3c6bac',
    messagingSenderId: '458041467333',
    projectId: 'roomrent-72633',
    storageBucket: 'roomrent-72633.firebasestorage.app',
    iosBundleId: 'com.example.homeForRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZM4-Vu9n4ITa6OSQgVs8AdqbziYlITs',
    appId: '1:458041467333:ios:dc521ad26943dcad3c6bac',
    messagingSenderId: '458041467333',
    projectId: 'roomrent-72633',
    storageBucket: 'roomrent-72633.firebasestorage.app',
    iosBundleId: 'com.example.homeForRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArofxRV-l8JJMdXPK4CrqrzGH55dR1XPk',
    appId: '1:458041467333:web:657efaeb33dd760a3c6bac',
    messagingSenderId: '458041467333',
    projectId: 'roomrent-72633',
    authDomain: 'roomrent-72633.firebaseapp.com',
    storageBucket: 'roomrent-72633.firebasestorage.app',
    measurementId: 'G-4LRFCHBBPX',
  );
}
